# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpd_app', '0002_drug_post_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_DB',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_text', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
            ],
        ),
    ]
