# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpd_app', '0003_police_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Posts',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_text', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
                ('encoded_image', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Police_DBs',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_text', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('encoded_image', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_text', models.CharField(max_length=255)),
                ('p_image', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('encoded_image', models.CharField(max_length=8000)),
            ],
        ),
        migrations.DeleteModel(
            name='Drug_Post',
        ),
        migrations.DeleteModel(
            name='Police_DB',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
