# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-10-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpd_app', '0004_auto_20220829_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('user_image', models.CharField(max_length=255)),
                ('encoded_image', models.TextField(max_length=8000)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
